#!/usr/bin/env bash

YELLOW='\033[1;33m'
NC='\033[0m' # No Color

clear

# export WWWGROUP=${WWWGROUP:-$(id -g)}
# export WWWUSER=${WWWUSER:-$(id -u)}

echo -e "${YELLOW}> Building...${NC}"

npm run build
docker build -t rakma/minizo:nightly -f docker/Dockerfile.prod .

# Push to Docker registry
read -p $'\033[1;33mDo you want to push to Docker registry? [y/N] \033[0m' -n 1 -r
echo    # Move to a new line

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${YELLOW}> Pushing image to Docker registry...${NC}"
    docker push rakma/minizo:nightly
fi

echo -e "${YELLOW}> Completed!${NC}"