version: "3"
services:
  minizo:
    image: rakma/minizo:latest
    # build: ./docker
    ports:
      - 3000:3000
    volumes:
      - .env:/srv/.env
      - /home/user/music:/music:rw
    user: 1000:1000
    restart: always

networks:
  default:
    name: minizo
    external: true