name: Mirror to Bitbucket

on:
  push:
    branches:
      - '**'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Push to Bitbucket
      env:
        BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
        BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
      run: |
        git remote add bitbucket https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@bitbucket.org/rakma/Minizo.git
        git push --mirror bitbucket
        git push --tags bitbucket  # Push all tags
